version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: course_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webapi:
    build: .
    container_name: course_api
    depends_on:
      - postgres
    volumes:
      - .:/app
      - app_bin:/app/bin
      - app_obj:/app/obj
      - nuget_cache:/root/.nuget/packages
    ports:
      - "8080:8080"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=course_db;Username=postgres;Password=postgres

volumes:
  postgres_data:
  app_bin:
  app_obj:
  nuget_cache:
